# Generated by Django 6.0.6 on 2026-07-09 11:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='patient_name',
            field=models.CharField(blank=True, default='Unknown Patient', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='raw_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='zone_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='diet_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='doctor_suggestion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='preventions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='xray_image',
            field=models.ImageField(blank=True, null=True, upload_to='xrays/'),
        ),
    ]
